### ISSUE TITLE
For images, Replace refs to static.openfoodfacts.org by images.openfoodfacts.org

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-explorer#122]
### Problem
For images, Replace refs to static.openfoodfacts.org by images.openfoodfacts.org

**Comment by VaiTon** [comment]
@teolemon where did you find the `static.off.org` url? I'm using the ones provided in the knowledge panels by the API (I think)

**Comment by teolemon** [comment]
I duplicated this issue to many repos, I might not have checked there actually was occurrences in there. Sorry @VaiTon

**Comment by VaiTon** [comment]
No worries!
