### ISSUE TITLE
Use the canonical wording for Eco-Score and Nutri-Score, add Nova - Ultra-processing levels

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-explorer#94]
### What
Use the canonical wording for Eco-Score and Nutri-Score, add Nova - Ultra-processing levels

<img width="540" alt="image" src="https://github.com/user-attachments/assets/5e21464e-d102-478f-8561-d7705df2c49f">

**Comment by VaiTon** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-explorer/commit/8c7176369840ee9bfce1ad1ef9a504bd118d5fcc
