### ISSUE TITLE
Language dropdown seems broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-explorer#95]
### What
Language dropdown seems broken

<img width="540" alt="image" src="https://github.com/user-attachments/assets/1fc1bda3-ce40-47fe-89ab-78c4c3f85562">

**Comment by VaiTon** [comment]
Fixed in https://github.com/openfoodfacts/openfoodfacts-explorer/commit/374d21ed74f2c03845fe017b2bad638c4ee0898a
